# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: llm_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11llm_service.proto\"\"\n\x0cInferRequest\x12\x12\n\ninput_text\x18\x01 \x01(\t\"$\n\rInferResponse\x12\x13\n\x0boutput_text\x18\x01 \x01(\t26\n\nLLMService\x12(\n\x05Infer\x12\r.InferRequest\x1a\x0e.InferResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llm_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INFERREQUEST']._serialized_start=21
  _globals['_INFERREQUEST']._serialized_end=55
  _globals['_INFERRESPONSE']._serialized_start=57
  _globals['_INFERRESPONSE']._serialized_end=93
  _globals['_LLMSERVICE']._serialized_start=95
  _globals['_LLMSERVICE']._serialized_end=149
# @@protoc_insertion_point(module_scope)
